name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: eu-west-2

    - name: Login to AWS ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry: 689346931712.dkr.ecr.eu-west-2.amazonaws.com
        access-key-id: ${{ secrets.ACCESS_KEY }}
        secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
